org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.15.3
fabric_api_version=0.141.4+1.21.11
owo_version=0.13.0+1.21.11
devauth_version=1.2.2
wynntils_version=4.2.7
wynntils_project_id=dU5Gb9Ab
wynntils_version_id=jeBTZ3Zn

mod_version=0.1.5
maven_group=org.kingdomfoxes.ralle
archives_base_name=ralle
