package org.kingdomfoxes.ralle.sound;

public enum RalleSoundCue {
    XYLOPHONE_D5,
    XYLOPHONE_E5,
    XYLOPHONE_F_SHARP_5,
    XYLOPHONE_G5,
    XYLOPHONE_A5,
    XYLOPHONE_B5,
    XYLOPHONE_C_SHARP_6,
    XYLOPHONE_D6,
    XYLOPHONE_E6,
    XYLOPHONE_F_SHARP_6,
    CHAT_COPY_SUCCESS,
    LFG_TOAST_IN,
    LFG_TOAST_OUT,
    LFG_RESONATE_1,
    LFG_RESONATE_2,
    LFG_RESONATE_3,
    LFG_RESONATE_4,
    LFG_FUNGUS_BREAK_4,
    KICK_EXPLOSION
}
